### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by tomek-he-him** [jonschlinkert/repeat-element#1]
Here’s what I get in a freshly checked-out repo ([4810bfd](https://github.com/jonschlinkert/repeat-element/tree/4810bfdaa6749c3f7e5013f2c23fe1bc43c61e1f)):

```
$ npm install >/dev/null && nmp test

> repeat-element@1.1.0 test <project-root>
> mocha -R spec

module.js:338
    throw err;
          ^
Error: Cannot find module '<project-root>/benchmark/code/undefined'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (<project-root>/test.js:22:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at <project-root>/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (<project-root>/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (<project-root>/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (<project-root>/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

**Comment by tomek-he-him** [comment]
:+1:
